-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Categories Table
create table public.categories (
  id text primary key,
  name text not null,
  description text,
  display_order integer default 99
);

-- Menu Items Table
create table public.menu_items (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  description text,
  price numeric not null,
  category text references public.categories(id),
  image_url text,
  featured boolean default false,
  available boolean default true,
  "spicyLevel" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reservations Table
create table public.reservations (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  email text not null,
  phone text not null,
  date text not null,
  time text not null,
  guests integer not null,
  special_requests text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages Table
create table public.messages (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text default 'unread',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Site Content Table (Key-Value Store for misc data like visitors)
create table public.site_content (
  key text primary key,
  value jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Gallery Images Table
create table public.gallery_images (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Page Content Table (Hero Sections)
create table public.page_content (
  page_slug text primary key,
  hero_title text,
  hero_subtitle text,
  hero_tagline text,
  hero_images text[],
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Home Page Features
create table public.home_features (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Home Page CTA
create table public.home_cta (
  id integer primary key default 1, -- Singleton
  title text,
  description text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 1)
);

-- About Page Story
create table public.about_story (
  id integer primary key default 1, -- Singleton
  paragraph1 text,
  paragraph2 text,
  paragraph3 text,
  images text[],
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 1)
);

-- About Page Values
create table public.about_values (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Team Members
create table public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  description text,
  image_url text,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contact Info
create table public.contact_info (
  id integer primary key default 1, -- Singleton
  copyright_text text,
  description text,
  tiktok_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 1)
);

-- Profiles Table (for Admin Users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique not null,
  email text unique not null,
  role text default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) Policies

-- Enable RLS
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;
alter table public.messages enable row level security;
alter table public.site_content enable row level security;
alter table public.gallery_images enable row level security;
alter table public.page_content enable row level security;
create policy "Admins can delete categories" on public.categories for delete using (auth.role() = 'authenticated');

-- Policies for Menu Items (Public Read, Admin Write)
create policy "Public menu items are viewable by everyone" on public.menu_items for select using (true);
create policy "Admins can insert menu items" on public.menu_items for insert with check (auth.role() = 'authenticated');
create policy "Admins can update menu items" on public.menu_items for update using (auth.role() = 'authenticated');
create policy "Admins can delete menu items" on public.menu_items for delete using (auth.role() = 'authenticated');

-- Policies for Reservations (Admin Read/Write, Public Insert)
create policy "Admins can view all reservations" on public.reservations for select using (auth.role() = 'authenticated');
create policy "Public can create reservations" on public.reservations for insert with check (true);
create policy "Admins can update reservations" on public.reservations for update using (auth.role() = 'authenticated');
create policy "Admins can delete reservations" on public.reservations for delete using (auth.role() = 'authenticated');

-- Policies for Messages (Admin Read/Write, Public Insert)
create policy "Admins can view all messages" on public.messages for select using (auth.role() = 'authenticated');
create policy "Public can create messages" on public.messages for insert with check (true);
create policy "Admins can update messages" on public.messages for update using (auth.role() = 'authenticated');
create policy "Admins can delete messages" on public.messages for delete using (auth.role() = 'authenticated');

-- Policies for Site Content (Public Read, Admin Write)
create policy "Public site content is viewable by everyone" on public.site_content for select using (true);
create policy "Admins can insert site content" on public.site_content for insert with check (auth.role() = 'authenticated');
create policy "Admins can update site content" on public.site_content for update using (auth.role() = 'authenticated');

-- Policies for Gallery Images (Public Read, Admin Write)
create policy "Public gallery images are viewable by everyone" on public.gallery_images for select using (true);
create policy "Admins can insert gallery images" on public.gallery_images for insert with check (auth.role() = 'authenticated');
create policy "Admins can update gallery images" on public.gallery_images for update using (auth.role() = 'authenticated');
create policy "Admins can delete gallery images" on public.gallery_images for delete using (auth.role() = 'authenticated');

-- Policies for Page Content (Public Read, Admin Write)
create policy "Public page content is viewable by everyone" on public.page_content for select using (true);
create policy "Admins can insert page content" on public.page_content for insert with check (auth.role() = 'authenticated');
create policy "Admins can update page content" on public.page_content for update using (auth.role() = 'authenticated');

-- Policies for Home Features (Public Read, Admin Write)
create policy "Public home features are viewable by everyone" on public.home_features for select using (true);
create policy "Admins can insert home features" on public.home_features for insert with check (auth.role() = 'authenticated');
create policy "Admins can update home features" on public.home_features for update using (auth.role() = 'authenticated');
create policy "Admins can delete home features" on public.home_features for delete using (auth.role() = 'authenticated');

-- Policies for Home CTA (Public Read, Admin Write)
create policy "Public home cta is viewable by everyone" on public.home_cta for select using (true);
create policy "Admins can insert home cta" on public.home_cta for insert with check (auth.role() = 'authenticated');
create policy "Admins can update home cta" on public.home_cta for update using (auth.role() = 'authenticated');

-- Policies for About Story (Public Read, Admin Write)
create policy "Public about story is viewable by everyone" on public.about_story for select using (true);
create policy "Admins can insert about story" on public.about_story for insert with check (auth.role() = 'authenticated');
create policy "Admins can update about story" on public.about_story for update using (auth.role() = 'authenticated');

-- Policies for About Values (Public Read, Admin Write)
create policy "Public about values are viewable by everyone" on public.about_values for select using (true);
create policy "Admins can insert about values" on public.about_values for insert with check (auth.role() = 'authenticated');
create policy "Admins can update about values" on public.about_values for update using (auth.role() = 'authenticated');
create policy "Admins can delete about values" on public.about_values for delete using (auth.role() = 'authenticated');

-- Policies for Team Members (Public Read, Admin Write)
create policy "Public team members are viewable by everyone" on public.team_members for select using (true);
create policy "Admins can insert team members" on public.team_members for insert with check (auth.role() = 'authenticated');
create policy "Admins can update team members" on public.team_members for update using (auth.role() = 'authenticated');
create policy "Admins can delete team members" on public.team_members for delete using (auth.role() = 'authenticated');

-- Policies for Contact Info (Public Read, Admin Write)
create policy "Public contact info is viewable by everyone" on public.contact_info for select using (true);
create policy "Admins can insert contact info" on public.contact_info for insert with check (auth.role() = 'authenticated');
create policy "Admins can update contact info" on public.contact_info for update using (auth.role() = 'authenticated');

-- Policies for Footer Info (Public Read, Admin Write)
create policy "Public footer info is viewable by everyone" on public.footer_info for select using (true);
create policy "Admins can insert footer info" on public.footer_info for insert with check (auth.role() = 'authenticated');
create policy "Admins can update footer info" on public.footer_info for update using (auth.role() = 'authenticated');

-- Note: Public needs to update 'site_visitors' key specifically? 
-- Ideally, use a stored procedure (RPC) for incrementing visitors to avoid opening up write access.
-- For now, allowing public update on 'site_visitors' key only could be risky without strict checks.
-- Better approach: Create a Postgres Function for incrementing visitors.

-- Function to increment visitors safely
create or replace function increment_visitors()
returns json
language plpgsql
security definer
as $$
declare
  current_count integer;
  new_count integer;
begin
  select (value->>'count')::integer into current_count from public.site_content where key = 'site_visitors';
  if current_count is null then
    current_count := 0;
  end if;
  new_count := current_count + 1;
  
  insert into public.site_content (key, value)
  values ('site_visitors', json_build_object('count', new_count))
  on conflict (key) do update set value = json_build_object('count', new_count);
  
  return json_build_object('count', new_count);
end;
$$;

-- Function to reset visitors (Admin only)
create or replace function reset_visitors()
returns json
language plpgsql
security definer
as $$
begin
  if auth.role() != 'authenticated' then
    raise exception 'Not authorized';
  end if;

  insert into public.site_content (key, value)
  values ('site_visitors', json_build_object('count', 0))
  on conflict (key) do update set value = json_build_object('count', 0);
  
  return json_build_object('count', 0, 'message', 'Visitor count reset');
end;
$$;

-- Daily Visitors Table (for analytics)
create table public.daily_visitors (
  date date primary key default CURRENT_DATE,
  count integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for daily_visitors
alter table public.daily_visitors enable row level security;

-- Policies for Daily Visitors
create policy "Public daily visitors are viewable by everyone" on public.daily_visitors for select using (true);
create policy "Admins can insert daily visitors" on public.daily_visitors for insert with check (auth.role() = 'authenticated');
create policy "Admins can update daily visitors" on public.daily_visitors for update using (auth.role() = 'authenticated');

-- Function to increment daily visitors safely
create or replace function increment_daily_visitors()
returns void
language plpgsql
security definer
as $$
begin
  insert into public.daily_visitors (date, count)
  values (CURRENT_DATE, 1)
  on conflict (date) do update set count = daily_visitors.count + 1, updated_at = now();
end;
$$;

-- Visitor Logs Table (for detailed analytics)
create table public.visitor_logs (
  id bigint generated by default as identity primary key,
  user_agent text,
  browser text,
  device_type text,
  os text,
  visited_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for visitor_logs
alter table public.visitor_logs enable row level security;

-- Policies for Visitor Logs
create policy "Public can insert visitor logs" on public.visitor_logs for insert with check (true);
create policy "Admins can view visitor logs" on public.visitor_logs for select using (auth.role() = 'authenticated');

-- Function to track visit (Log + Increment Daily)
create or replace function track_visit(
  p_user_agent text,
  p_browser text,
  p_device_type text,
  p_os text
)
returns void
language plpgsql
security definer
as $$
begin
  -- 1. Log the individual visit
  insert into public.visitor_logs (user_agent, browser, device_type, os)
  values (p_user_agent, p_browser, p_device_type, p_os);

  -- 2. Increment daily counter
  insert into public.daily_visitors (date, count)
  values (CURRENT_DATE, 1)
  on conflict (date) do update set count = daily_visitors.count + 1, updated_at = now();
  
  -- 3. Increment total counter (legacy support, optional but good for consistency)
  insert into public.site_content (key, value)
  values ('site_visitors', json_build_object('count', 1))
  on conflict (key) do update set value = json_build_object('count', ((site_content.value->>'count')::int + 1));
end;
$$;

-- Fix RLS for site_content (Public Read)
drop policy if exists "Public site content is viewable by everyone" on public.site_content;
create policy "Public site content is viewable by everyone" on public.site_content for select using (true);

-- Ensure Daily Visitors policies are correct
drop policy if exists "Public daily visitors are viewable by everyone" on public.daily_visitors;
create policy "Public daily visitors are viewable by everyone" on public.daily_visitors for select using (true);

-- Ensure Visitor Logs policies are correct
drop policy if exists "Public can insert visitor logs" on public.visitor_logs;
create policy "Public can insert visitor logs" on public.visitor_logs for insert with check (true);

-- Storage Bucket (Attempt to create if extension enabled, otherwise user must create in dashboard)
insert into storage.buckets (id, name, public) values ('images', 'images', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access" on storage.objects for select using ( bucket_id = 'images' );
create policy "Admin Upload" on storage.objects for insert with check ( bucket_id = 'images' and auth.role() = 'authenticated' );
create policy "Admin Update" on storage.objects for update using ( bucket_id = 'images' and auth.role() = 'authenticated' );
create policy "Admin Delete" on storage.objects for delete using ( bucket_id = 'images' and auth.role() = 'authenticated' );
